const viState = {
    lan: 'vi',
    cart: 'Giỏ hàng',
    VPP: 'VPP & học cụ',
    type: 'Thể loại',
    login: 'Đăng nhập',
    logout: 'Đăng xuất',
    search: 'Tìm kiếm',
    slogan: 'Cách dễ nhất để tìm sách tốt nhất!',
    let: 'Chọn sách ngay',
    author: 'Tác giả',
    price: 'Giá',
    bookResultTitle: 'Các sách tìm được:',
    authorResultTitle: 'Các tác giả liên quan:',
    sortBy: 'Sắp xếp theo: ',
    priceFrom: 'Giá từ: ',
    category: 'Thể loại: ',
    username: 'Tên đăng nhập',
    password: 'Mật khẩu',
    requiredUsername: 'Bạn cần nhập tên đăng nhập!',
    requiredPassword: 'Bạn cần nhập mật khẩu!',
    name: 'Họ tên',
    repeatPassword: 'Nhập lại mật khẩu',
    requiredName: 'Bạn cần nhập họ tên!',
    requiredRepeatPassword: 'Bạn cần nhập lại mật khẩu!',
    phone: 'Số điện thoại',
    gender: 'Giới tính',
    selectGender: 'Chọn giới tính của bạn',
    requireGender: 'Bạn cần chọn giới tính!',
    requirePhone: 'Bạn cần nhập số điện thoại!',
    register: 'Đăng ký',
    male: 'Nam',
    female: 'Nữ',
    agreement: 'Tôi đã đọc điều khoản sử dụng',
    requiredAgreement: 'Để sử dụng dịch vụ của chúng tôi bạn cần chấp nhận điều khoản sử dụng',
    failConfirmPassword: 'Xác nhận mật khẩu không thành công!',
    requireEmail: 'Bạn cần nhập email!',
    invalidEmail: 'Email không đúng định dạng!',
    tooltipName: 'Bạn muốn chúng tôi gọi bạn là gi?',
    tooltipUserName: 'Tên bạn sẽ sử dụng để đăng nhập',
    update: 'Cập nhật',
    bestseller: 'Sách nổi bật',
    popAuthor: 'Tác giả phổ biến',
    pupDate: 'Ngày xuất bản',
    pupCompany: 'Nhà xuất bản',
    corverForm: 'Hình thức bìa',
    DeliveryTime: 'Thời gian giao hàng',
    DeliveryTimeRe: '5 ngày kể từ ngày đặt',
    ReturnPolicy: 'Chính sách đổi trả',
    ReturnPolicyRe: 'Chỉ áp dụng đổi trả khi sản phẩm bị lỗi giao hàng',
    quantity: 'Số lượng',
    addToCart: 'Thêm vào giỏ hàng',
    total: 'Tổng tiền',
    transFee: 'Phí vận chuyển',
    summary: 'Tổng hợp',
    Order: 'Đặt hàng',
    acc: 'Tài khoản',
    historyOrder: 'Lịch sử đặt hàng',
    logout: 'Đăng xuất',
};
const enState = {
    lan: 'en',
    cart: 'Cart',
    VPP: 'Stationery & tools',
    type: 'Category',
    login: 'Login',
    logout: 'Logout',
    search: 'Search',
    slogan: 'The easiest way to find the best books!',
    let: 'Choose a book now',
    author: 'Author',
    price: 'Price',
    bookResultTitle: 'Books found:',
    authorResultTitle: 'Related Authors:',
    sortby: 'Sorted by: ',
    priceFrom: 'Price from: ',
    category: 'Category: ',
    username: 'Username',
    password: 'Password',
    requiredUsername: 'Please input your username!',
    requiredPassword: 'Please input your password!',
    name: 'Name',
    repeatPassword: 'Confirm password',
    requiredName: 'Please input your name!',
    requiredRepeatPassword: 'Please confirm password!',
    phone: 'Phone Number',
    gender: 'Gender',
    selectGender: 'Select your gender!',
    requireGender: 'Please select your gender!',
    requirePhone: 'Please input your phone number!',
    register: 'Register',
    male: 'Male',
    female: 'Female',
    agreement: 'I have read the agreement',
    requiredAgreement: 'Should accept agreement',
    failConfirmPassword: 'The two passwords that you entered do not match!',
    requireEmail: 'Please input your E-mail!',
    invalidEmail: 'The input is not valid E-mail!',
    tooltipName: 'What do you want others to call you?',
    tooltipUserName: 'The name you will use to log in',
    update: 'update',
    bestseller: 'Best Seller',
    popAuthor: 'Popular author',
    pupDate: 'Publication date',
    pupCompany: 'Publication company',
    corverForm: 'Cover form',
    DeliveryTime: 'Delivery time',
    DeliveryTimeRe: '5 days from the date of booking',
    ReturnPolicy: 'Return Policy',
    quantity: 'Quantity',
    addToCart: 'Add to cart',
    ReturnPolicyRe: 'Refunds are only applicable when the product is defective in delivery',
    total: 'Total',
    transFee: 'Transport fee',
    summary: 'Summary',
    Order: 'Order',
    acc: 'Account',
    profile: 'Profile',
    historyOrder: 'History Order',
    logout: 'Log out',
};

const lanReducer = (state = viState, action) => {
    switch (action.type) {
        case 'TO_VI': {
            return viState;
        }
        case 'TO_EN': {
            return enState;
        }
        default:
            return viState;
    }
};
export default lanReducer;
